"""
Stub for ethereum_types.numeric.

`Unsigned` intentionally does NOT list `int` as a base class. mypy therefore
treats `Uint` as incompatible with `int`, preventing LSP violations at
type-check time. At runtime the implementation subclasses `int` for speed.
"""

from typing import ClassVar, Literal, Optional, Sized, SupportsInt, Tuple, Type, Union

from typing_extensions import Self, override

from .bytes import Bytes, Bytes1, Bytes4, Bytes8, Bytes32, Bytes64

_BytesLike = Union[bytes, bytearray, memoryview]

class Unsigned:
    """Base of integer types. NOT a subclass of int (type-check only)."""

    def __new__(cls, value: SupportsInt) -> Self: ...
    def __abs__(self) -> Self: ...

    # Arithmetic
    def __add__(self, right: Self) -> Self: ...
    def __radd__(self, left: Self) -> Self: ...
    def __iadd__(self, right: Self) -> Self: ...
    def __sub__(self, right: Self) -> Self: ...
    def __rsub__(self, left: Self) -> Self: ...
    def __isub__(self, right: Self) -> Self: ...
    def __mul__(self, right: Self) -> Self: ...
    def __rmul__(self, left: Self) -> Self: ...
    def __imul__(self, right: Self) -> Self: ...
    def __truediv__(self, other: Self) -> float: ...
    def __rtruediv__(self, other: Self) -> float: ...
    def __floordiv__(self, right: Self) -> Self: ...
    def __rfloordiv__(self, left: Self) -> Self: ...
    def __ifloordiv__(self, right: Self) -> Self: ...
    def __mod__(self, right: Self) -> Self: ...
    def __rmod__(self, left: Self) -> Self: ...
    def __imod__(self, right: Self) -> Self: ...
    def __divmod__(self, right: Self) -> Tuple[Self, Self]: ...
    def __rdivmod__(self, left: Self) -> Tuple[Self, Self]: ...
    def __pow__(self, right: Self, modulo: Optional[Self] = ...) -> Self: ...
    def __rpow__(self, left: Self, modulo: Optional[Self] = ...) -> Self: ...
    def __ipow__(self, right: Self, modulo: Optional[Self] = ...) -> Self: ...

    # Bitwise
    def __xor__(self, right: Self) -> Self: ...
    def __rxor__(self, left: Self) -> Self: ...
    def __ixor__(self, right: Self) -> Self: ...
    def __and__(self, other: Self) -> Self: ...
    def __rand__(self, other: Self) -> Self: ...
    def __or__(self, other: Self) -> Self: ...
    def __ror__(self, other: Self) -> Self: ...
    def __lshift__(self, right: Self) -> Self: ...
    def __rlshift__(self, left: Self) -> Self: ...
    def __rshift__(self, right: Self) -> Self: ...
    def __rrshift__(self, left: Self) -> Self: ...
    def __invert__(self) -> Self: ...

    # Unary / conversions
    def __neg__(self) -> int: ...
    def __pos__(self) -> Self: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __floor__(self) -> Self: ...
    def __ceil__(self) -> Self: ...
    def __round__(self, ndigits: Optional[int] = ...) -> Self: ...
    def __trunc__(self) -> Self: ...

    # Comparisons / truthiness
    def __bool__(self) -> bool: ...
    @override
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: Self) -> bool: ...
    def __le__(self, other: Self) -> bool: ...
    def __gt__(self, other: Self) -> bool: ...
    def __ge__(self, other: Self) -> bool: ...
    @override
    def __hash__(self) -> int: ...

    # Representation
    @override
    def __repr__(self) -> str: ...
    @override
    def __str__(self) -> str: ...

    # Byte serialization
    def to_be_bytes64(self) -> Bytes64: ...
    def to_be_bytes32(self) -> Bytes32: ...
    def to_bytes1(self) -> Bytes1: ...
    def to_le_bytes4(self) -> Bytes4: ...
    def to_be_bytes4(self) -> Bytes4: ...
    def to_le_bytes8(self) -> Bytes8: ...
    def to_be_bytes8(self) -> Bytes8: ...
    def to_bytes(
        self,
        length: Optional[Self] = ...,
        byteorder: Literal["big", "little"] = ...,
    ) -> Bytes: ...
    def to_be_bytes(self) -> Bytes: ...
    def to_le_bytes(self) -> Bytes: ...
    def to_le_bytes32(self) -> Bytes32: ...
    def to_le_bytes64(self) -> Bytes64: ...
    def bit_length(self) -> "Uint": ...

class Uint(Unsigned):
    """Unsigned integer of arbitrary size."""

    @classmethod
    def from_be_bytes(cls: Type[Self], buffer: _BytesLike) -> Self: ...
    @classmethod
    def from_le_bytes(cls: Type[Self], buffer: _BytesLike) -> Self: ...

def ulen(input: Sized, /) -> Uint: ...

class FixedUnsigned(Unsigned):
    """Superclass for fixed size unsigned integers."""

    MAX_VALUE: ClassVar[Self]

    @classmethod
    def from_be_bytes(cls: Type[Self], buffer: _BytesLike) -> Self: ...
    @classmethod
    def from_le_bytes(cls: Type[Self], buffer: _BytesLike) -> Self: ...
    @classmethod
    def from_signed(cls: Type[Self], value: int) -> Self: ...
    def wrapping_add(self, right: Self) -> Self: ...
    def wrapping_sub(self, right: Self) -> Self: ...
    def wrapping_mul(self, right: Self) -> Self: ...
    def wrapping_pow(
        self, right: Self, modulo: Optional[Self] = ...
    ) -> Self: ...
    def to_signed(self) -> int: ...
    @override
    def __invert__(self) -> Self: ...

class U256(FixedUnsigned):
    MAX_VALUE: ClassVar["U256"]

class U64(FixedUnsigned):
    MAX_VALUE: ClassVar["U64"]

class U32(FixedUnsigned):
    MAX_VALUE: ClassVar["U32"]

class U16(FixedUnsigned):
    MAX_VALUE: ClassVar["U16"]

class U8(FixedUnsigned):
    MAX_VALUE: ClassVar["U8"]
