name: Tests

on:
  push:
    branches:
      - master
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        py: [ "3.11", "pypy3.11" ]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}

      - name: Install Hatch
        run: "pip install hatch==1.16.5"

      - name: Run Hatch (CPython)
        if: "${{ !startsWith(matrix.py, 'pypy') }}"
        run: |
          hatch fmt --check
          hatch test
          hatch build

      - name: Run Hatch (PyPy)
        if: "${{ startsWith(matrix.py, 'pypy') }}"
        run: hatch test
